# Generated by Django 4.2.7 on 2024-11-06 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='创建者')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='更新者')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='监控对象')),
                ('type', models.CharField(max_length=50, verbose_name='监控对象类型')),
                ('description', models.TextField(blank=True, verbose_name='监控对象描述')),
            ],
            options={
                'verbose_name': '监控对象',
                'verbose_name_plural': '监控对象',
            },
        ),
        migrations.CreateModel(
            name='MonitorInstanceGroupingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='创建者')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='更新者')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=100, verbose_name='分组规则名称')),
                ('type', models.CharField(choices=[('select', 'Select'), ('condition', 'Condition')], max_length=30, verbose_name='分组规则类型')),
                ('organizations', models.JSONField(default=list, verbose_name='所属组织')),
                ('grouping_rules', models.JSONField(default=dict, verbose_name='分组规则详情')),
                ('monitor_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.monitorobject', verbose_name='监控对象')),
            ],
            options={
                'verbose_name': '监控实例分组规则',
                'verbose_name_plural': '监控实例分组规则',
            },
        ),
        migrations.CreateModel(
            name='MetricGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='创建者')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='更新者')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=100, verbose_name='指标分组名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='指标分组描述')),
                ('monitor_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.monitorobject', verbose_name='指标对象')),
            ],
            options={
                'verbose_name': '指标分组',
                'verbose_name_plural': '指标分组',
            },
        ),
        migrations.CreateModel(
            name='MonitorInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='创建者')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='更新者')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('instance_id', models.CharField(db_index=True, max_length=100, verbose_name='监控对象实例id')),
                ('organization', models.CharField(db_index=True, max_length=100, verbose_name='组织id')),
                ('monitor_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.monitorobject', verbose_name='监控对象')),
            ],
            options={
                'verbose_name': '监控对象实例',
                'verbose_name_plural': '监控对象实例',
                'unique_together': {('monitor_object', 'instance_id', 'organization')},
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='创建者')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='更新者')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=100, verbose_name='指标名称')),
                ('type', models.CharField(max_length=50, verbose_name='指标类型')),
                ('description', models.TextField(blank=True, null=True, verbose_name='指标描述')),
                ('dimensions', models.JSONField(default=list, verbose_name='维度')),
                ('metric_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.metricgroup', verbose_name='指标分组')),
                ('monitor_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.monitorobject', verbose_name='指标对象')),
            ],
            options={
                'verbose_name': '指标',
                'verbose_name_plural': '指标',
                'unique_together': {('monitor_object', 'name')},
            },
        ),
    ]
