# Generated by Django 4.2.7 on 2024-11-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='data_type',
            field=models.CharField(default='', max_length=50, verbose_name='数据类型'),
        ),
        migrations.AddField(
            model_name='metric',
            name='display_name',
            field=models.CharField(default='', max_length=100, verbose_name='指标展示名称'),
        ),
        migrations.AddField(
            model_name='metric',
            name='query',
            field=models.TextField(default='', verbose_name='查询语句'),
        ),
        migrations.AddField(
            model_name='metric',
            name='unit',
            field=models.CharField(default='', max_length=50, verbose_name='指标单位'),
        ),
    ]
