# Generated by Django 4.2.7 on 2024-11-25 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorobject',
            name='level',
            field=models.CharField(default='base', max_length=50, verbose_name='监控对象级别'),
        ),
        migrations.AddField(
            model_name='monitorobject',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='monitor.monitorobject', verbose_name='父级监控对象'),
        ),
    ]
