# Generated by Django 4.2.7 on 2024-11-21 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitorpolicy',
            name='frequency',
        ),
        migrations.AddField(
            model_name='monitorpolicy',
            name='schedule',
            field=models.JSONField(default=dict, verbose_name='策略执行周期(crontab格式)'),
        ),
    ]
