# Generated by Django 4.2.7 on 2024-11-08 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='metricgroup',
            unique_together={('monitor_object', 'name')},
        ),
    ]
