# Generated by Django 4.2.7 on 2024-11-26 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_monitorobject_level_monitorobject_parent'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monitorinstance',
            unique_together=set(),
        ),
    ]
