# Generated by Django 4.2.7 on 2024-11-13 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_alter_metricgroup_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monitorinstance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='monitorinstance',
            name='agent_id',
            field=models.CharField(default='', max_length=100, verbose_name='Agent ID'),
        ),
        migrations.AddField(
            model_name='monitorinstance',
            name='auto',
            field=models.BooleanField(default=False, verbose_name='是否自动创建'),
        ),
        migrations.AddField(
            model_name='monitorinstance',
            name='interval',
            field=models.IntegerField(default=10, verbose_name='监控实例采集间隔(s)'),
        ),
        migrations.AddField(
            model_name='monitorinstance',
            name='name',
            field=models.CharField(db_index=True, default='', max_length=100, verbose_name='监控对象实例名称'),
        ),
        migrations.AlterField(
            model_name='monitorinstance',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='监控对象实例ID'),
        ),
        migrations.AlterUniqueTogether(
            name='monitorinstance',
            unique_together={('monitor_object', 'name')},
        ),
        migrations.RemoveField(
            model_name='monitorinstance',
            name='instance_id',
        ),
        migrations.RemoveField(
            model_name='monitorinstance',
            name='organization',
        ),
        migrations.CreateModel(
            name='MonitorInstanceOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='创建者')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='更新者')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('organization', models.CharField(max_length=100, verbose_name='组织id')),
                ('monitor_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.monitorinstance', verbose_name='监控对象实例')),
            ],
            options={
                'verbose_name': '监控对象实例组织',
                'verbose_name_plural': '监控对象实例组织',
                'unique_together': {('monitor_instance', 'organization')},
            },
        ),
    ]
