# Generated by Django 4.2.7 on 2024-11-28 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_monitoralert_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoralert',
            name='operator',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='告警处理人'),
        ),
    ]
