# Generated by Django 4.2.7 on 2024-11-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_alter_monitoralert_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoralert',
            name='value',
            field=models.FloatField(blank=True, null=True, verbose_name='最高告警值'),
        ),
        migrations.AlterField(
            model_name='monitoralert',
            name='level',
            field=models.CharField(default='', max_length=20, verbose_name='最高告警级别'),
        ),
        migrations.AlterField(
            model_name='monitorevent',
            name='value',
            field=models.FloatField(blank=True, null=True, verbose_name='事件值'),
        ),
    ]
