# Generated by Django 4.2.7 on 2024-11-28 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_monitoralert_value_alter_monitoralert_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoralert',
            name='content',
            field=models.TextField(blank=True, verbose_name='告警内容'),
        ),
        migrations.AddField(
            model_name='monitorevent',
            name='content',
            field=models.TextField(blank=True, verbose_name='事件内容'),
        ),
        migrations.AlterField(
            model_name='monitoralert',
            name='monitor_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitor.monitorinstance', verbose_name='监控实例'),
        ),
        migrations.AlterField(
            model_name='monitoralert',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitor.monitorpolicy', verbose_name='监控策略'),
        ),
        migrations.AlterField(
            model_name='monitorevent',
            name='monitor_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitor.monitorinstance', verbose_name='监控实例'),
        ),
        migrations.AlterField(
            model_name='monitorevent',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitor.monitorpolicy', verbose_name='监控策略'),
        ),
    ]
