# Generated by Django 4.2.7 on 2024-12-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0008_alter_monitoralert_monitor_instance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorpolicy',
            name='filter',
            field=models.JSONField(default=list, verbose_name='过滤条件'),
        ),
    ]
