# Generated by Django 4.2.7 on 2024-12-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0009_monitorpolicy_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorpolicy',
            name='no_data_level',
            field=models.CharField(default='no_data', max_length=20, verbose_name='无数据告警级别'),
        ),
    ]
