# Generated by Django 4.2.7 on 2024-12-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0010_monitorpolicy_no_data_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitorpolicy',
            name='no_data_level',
            field=models.CharField(default='', max_length=20, verbose_name='无数据告警级别'),
        ),
    ]
