# Generated by Django 4.2.7 on 2024-12-05 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0011_alter_monitorpolicy_no_data_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitorpolicy',
            name='query',
        ),
        migrations.AlterField(
            model_name='monitorpolicy',
            name='schedule',
            field=models.JSONField(default=dict, verbose_name='策略执行周期'),
        ),
    ]
