# Generated by Django 4.2.7 on 2024-12-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0013_remove_monitorevent_monitor_instance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('policy_id', models.IntegerField(db_index=True, default=0, verbose_name='监控策略ID')),
                ('monitor_instance_id', models.CharField(db_index=True, default='', max_length=100, verbose_name='监控对象实例ID')),
                ('alert_type', models.CharField(choices=[('alert', 'Alert'), ('no_data', 'No Data')], default='alert', max_length=50, verbose_name='告警类型')),
                ('level', models.CharField(default='', max_length=20, verbose_name='最高告警级别')),
                ('value', models.FloatField(blank=True, null=True, verbose_name='最高告警值')),
                ('content', models.TextField(blank=True, verbose_name='告警内容')),
                ('status', models.CharField(choices=[('new', 'New'), ('closed', 'Closed'), ('recovered', 'Recovered')], db_index=True, default='new', max_length=20, verbose_name='告警状态')),
                ('start_event_id', models.IntegerField(blank=True, null=True, verbose_name='开始事件ID')),
                ('start_event_time', models.DateTimeField(blank=True, null=True, verbose_name='开始事件时间')),
                ('end_event_id', models.IntegerField(blank=True, null=True, verbose_name='结束事件ID')),
                ('end_event_time', models.DateTimeField(blank=True, null=True, verbose_name='结束事件时间')),
                ('operator', models.CharField(blank=True, max_length=50, null=True, verbose_name='告警处理人')),
            ],
            options={
                'verbose_name': '监控告警',
                'verbose_name_plural': '监控告警',
            },
        ),
        migrations.CreateModel(
            name='MonitorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_id', models.IntegerField(db_index=True, verbose_name='监控策略ID')),
                ('monitor_instance_id', models.CharField(db_index=True, max_length=100, verbose_name='监控对象实例ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='事件生成时间')),
                ('value', models.FloatField(blank=True, null=True, verbose_name='事件值')),
                ('level', models.CharField(choices=[('no_data', 'No Data'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], max_length=20, verbose_name='事件级别')),
                ('content', models.TextField(blank=True, verbose_name='事件内容')),
                ('notice_result', models.BooleanField(default=True, verbose_name='通知结果')),
            ],
        ),
    ]
