# Generated by Django 4.2.7 on 2024-12-06 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0014_monitoralert_monitorevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorpolicy',
            name='group_by',
            field=models.JSONField(default=list, verbose_name='分组字段'),
        ),
    ]
