# Generated by Django 4.2.7 on 2024-12-10 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0017_monitorpolicy_last_run_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorPlugin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='创建者')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='更新者')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=100, verbose_name='插件名称')),
                ('description', models.TextField(blank=True, verbose_name='插件描述')),
                ('monitor_object', models.ManyToManyField(to='monitor.monitorobject', verbose_name='监控对象')),
            ],
            options={
                'verbose_name': '监控插件',
                'verbose_name_plural': '监控插件',
            },
        ),
        migrations.AddField(
            model_name='metric',
            name='monitor_plugin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitor.monitorplugin', verbose_name='监控插件'),
        ),
    ]
