# Generated by Django 4.2.7 on 2024-12-10 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0020_monitorevent_notice_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitorplugin',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='插件名称'),
        ),
    ]
