# Generated by Django 4.2.7 on 2024-12-10 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0021_alter_monitorplugin_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metric',
            name='type',
        ),
    ]
