# Generated by Django 4.2.7 on 2024-12-17 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0024_remove_metricgroup_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='is_pre',
            field=models.BooleanField(default=True, verbose_name='是否预定义'),
        ),
        migrations.AddField(
            model_name='metricgroup',
            name='is_pre',
            field=models.BooleanField(default=True, verbose_name='是否预定义'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='unit',
            field=models.TextField(default='', verbose_name='指标单位'),
        ),
    ]
