# Generated by Django 4.2.7 on 2024-12-19 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0028_alter_monitorinstance_id_alter_monitorinstance_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitorpolicy',
            name='period',
        ),
    ]
