# Generated by Django 4.2.7 on 2024-12-19 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0029_remove_monitorpolicy_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorpolicy',
            name='period',
            field=models.JSONField(default=dict, verbose_name='每次监控检测的数据周期,eg: 1h内, 5m内'),
        ),
        migrations.AlterField(
            model_name='monitorpolicy',
            name='schedule',
            field=models.JSONField(default=dict, verbose_name='策略执行周期, eg: 1h执行一次, 5m执行一次'),
        ),
    ]
